# Coding Attention Mechanism

## Simple Self-Attention Without Trainable Weights

Let's create a simple example:

In [2]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

inputs.shape # [token, embedding_dim]

torch.Size([6, 3])

In [4]:
query_2 = inputs[1] # 2nd input token is the query
attention_scores_2 = torch.empty(inputs.shape[0])

# compute attention scores
for i, input_embedding in enumerate(inputs):
  attention_scores_2[i] = torch.dot(query_2, input_embedding)

attention_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [5]:
# compute attention weights
attention_weights_2 = torch.softmax(attention_scores_2, dim=0)

print("attention weights: ", attention_weights_2)
print("sum:", attention_weights_2.sum())

attention weights:  tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
sum: tensor(1.)


In [7]:
# compute context vector
context_vector_2 = torch.zeros(inputs.shape[1])

for i, input_embedding in enumerate(inputs):
  context_vector_2 += attention_weights_2[i] * input_embedding

context_vector_2

tensor([0.4419, 0.6515, 0.5683])

Let's compute for all queries simultaneously using matrices:

In [8]:
# compute attention scores
attention_scores = inputs @ inputs.T
attention_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [9]:
# compute attention weights
attention_weights = torch.softmax(attention_scores, dim=-1)
print("row sums:", attention_weights.sum(dim=-1))
attention_weights

row sums: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [10]:
# compute context vectors
context_vectors = attention_weights @ inputs
context_vectors

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

## Implement Self-Attention with Trainable Weights